### ISSUE TITLE
How to edit the backblast after posting?

### ISSUE THREAD

**Issue by gdhugo** [F3Nation-Community/slackblast#10]
Great tool! One question: is there any way to edit the bost's post after it is posted to the channel? For example, Q makes an error and wants to fix it, etc.

I am hoping there is some way to set the permissions for the bot's posts but not finding much after googling on this.

**Comment by srschaecher** [comment]
The app would have to post as the user, rather than as the slack app. That *should* allow the user to edit it.
It is possible to grant an app User Scope privs that should allow it to post as the user. @wolfpackt99 have you looked into using this with user scopes rather than posting as the slackblast app?

**Comment by willhlaw** [comment]
That's a great idea, @srschaecher. I wasn't sure how we would tackle this. I remember @wolfpackt99 or @yankeestom mentioning they wanted to take a stab at allowing edit post feature. Any update guys? 

@srschaecher, would you have the chops to take a stab at this? I have a Slack environment, https://f3nation-community.slack.com/, to play with on your local python environment.

**Comment by willhlaw** [comment]
It's not looking too good. Their only seems to be one approach and that is to ask each user for permission and saving their user tokens, so not only is that a pain to go through the OAuth mumbo jumbo and not that great of an end user experience, but I think we would need to have a persistent store for each user token and keep it nice and secure and organized. Below are my findings.

> It is only possible to edit your own messages (assuming this is allows in your workspace), but never the messages of others. That is the same for all users including admins and owners. And its the same with the API method chat.update.
>
> But there is a workaround: Your app can gather tokens from every user in your workspace and then use those token to impersonate each users allowing your app to change every message. This will require each user to install the app once. Your app then just needs to use the matching token to update each message.
>
> Note that this workaround has some obvious drawbacks, e.g. giving your app access to all message and channels on the workspace and also requires some organizational effort to maintain.

- https://stackoverflow.com/a/56443230

> Having the user's token
>
> Another approach is to always use the token from the respective user for sending the message. In combination with as_user = true messages sent by your app will look exactly as if they would come from the respective user (no APP tag).
>
> To make that happen your app would need to collect tokens from all users on your workspace and store them for later use. This can be done by asking every user to install your app (called adding a "configuration") through the Oauth process (same you use to install your app to a workspace), which allows your app to collect and store those tokens for later use.

- https://stackoverflow.com/questions/42658126/is-it-possible-to-post-to-chat-postmessage-as-any-user-in-a-slack-team

**Comment by willhlaw** [comment]
Best workaround for now until somebody comes up with another idea or has a plan for persistent storage for every user's tokens is this:

1. If you want to edit a post, copy the main body
2. Delete the post
3. Create another post and save time by pasting into the main body

I'm closing this for now.

**Comment by willhlaw** [comment]
From Sept. 13 Slack conversation.

Beaker: I havent spent any time digging into SlackBlast personally, but what options do we have to make a centralized SlackBlast server instead of of making every region set up their own Azure instance? Seems we could just run it on the PAXminer server? The SlackBlast server would just lookup the region Slack workspace auth info from the database the same way PAXminer does.

Each region/slack workspace has to have a separate OAuth token. I have a restricted database table that PAXminer calls to retrieve that token for each region as it executes that region. So in this case, when SlackBlast posts a request from Slack to SlackBlast, it would just have to retrieve the appropriate region token from the database and then use that to push the message back to Slack. 

@srschaecher @wolfpackt99
